BUG: Fix runtime error related to missing EditorWidget
This commit fixes a regression most likely introduced by r24155 (ENH: Fixes
#3549. Import scripted module as python module)

Error fixed by this commit is the following:

//-------------
File "/home/jcfr/.config/NA-MIC/Extensions-24305/LongitudinalPETCT/lib/Slicer-4.4/qt-loadable-modules/Python/qSlicerLongitudinalPETCTModuleWidget.py", line 99, in __createEditorWidget
  self.editorWidget = EditorWidget(editorWidgetParent, False)
NameError: global name 'EditorWidget' is not defined
//-------------