BUG: Fix runtime error related to missing LabelStatisticsLogic. Fixes #5
This commit fixes a regression most likely introduced by r24155 (ENH: Fixes
#3549. Import scripted module as python module)

Error fixed by this commit is the following:

//-------------
File "/home/jcfr/.config/NA-MIC/Extensions-24309/LongitudinalPETCT/lib/Slicer-4.4/qt-loadable-modules/Python/qSlicerLongitudinalPETCTModuleWidget.py", line 1445, in calculateSUVsAndStatistics
  stats = LabelStatisticsLogic(study.GetPETVolumeNode(), study.GetPETLabelVolumeNode())
NameError: global name 'LabelStatisticsLogic' is not defined
//-------------